export const FETCH_DASHBOARDBINFO = 'FETCH_DASHBOARDBINFO';
export const FETCH_DASHBOARDCLOGS = 'FETCH_DASHBOARDCLOGS';
export const FETCH_COURSES = 'FETCH_COURSES';
export const GET_PROFESOR = 'GET_PROFESOR';
export const GET_ALUMNOS = 'GET_ALUMNOS';
export const ALUMNO = 5;
export const PROFESOR = 3;
export const COORDINADOR = 1;